solvebio/errors.py

error handling and just prints the error sent by the API

some error responses were not being parsed correctly; this simplifies

---

setup.py
solvebio/__init__.py
solvebio/cli/ipython.py
solvebio/exporters.py
solvebio/query.py
solvebio/resource/__init__.py
solvebio/resource/apiresource.py
solvebio/resource/dataset.py
solvebio/resource/datasetexport.py
solvebio/test/test_exports.py
solvebio/test/test_upload.py

Deprecates client-side "Exporters"

Add support for DatasetExports

---

solvebio/__init__.py
solvebio/annotate.py
solvebio/cli/ipython.py
solvebio/query.py
solvebio/test/test_annotate.py
solvebio/test/test_login.py

Uses the annotate endpoint which can add fields to lists of records.
Related to #146 
Supports the following usage:
```python
import solvebio
from solvebio import Dataset
solvebio.login()
query = Dataset("ClinVar/Variants")\
.query(fields=["variant_sbid", "rs_id", "rcv_accession", "phenotype"])\
.filter(clinical_significance="pathogenic")\
fields = [
{
"name": "civic_count",
"data_type": "integer",
"expression": """
dataset_count(
'CIViC/Variants',
entities=[('variant', record.variant_sbid)]
)
"""
}
]
for record in query.annotate(fields):
if record['civic_count'] > 0:
print record
```

Add Annotator and Expression support

---

solvebio/query.py

previously sending this filter
```
>>> filters = ~ Filter(ac_score=None, original_ac_score=None)
>>> print filters.filters
[{'not': {'and': [('original_ac_score', None), ('ac_score', None)]}}]
```
would end up sending the following to the API:  
```
["not","and"]
```

update filter creation to correctly handle nested dict filters

---

solvebio/resource/dataset.py
solvebio/resource/datasetexport.py

incorrect filter parameter was causing all of the user's dataset activity to be followed

incorrect filter parameter

---

CHANGELOG.md
solvebio/resource/dataset.py
solvebio/resource/datasetcommit.py
solvebio/resource/datasetexport.py
solvebio/resource/datasetimport.py
solvebio/resource/datasetmigration.py
solvebio/resource/object.py
solvebio/resource/task.py
solvebio/resource/vault.py
solvebio/test/client_mocks.py
solvebio/test/test_dataset.py
solvebio/test/test_dataset_migrations.py
solvebio/test/test_exports.py

- update retrieval to properly handle SolveClient
- make them properties
- add dataset id shortcut also
- add shortcuts to get Dataset vault_object
- add shortcuts to get Object vault and Object parent

update retrieval of datasets by jobs/tasks

---

README.md
solvebio/cli/data.py
solvebio/cli/main.py
solvebio/client.py
solvebio/resource/apiresource.py
solvebio/resource/dataset.py
solvebio/resource/object.py
solvebio/resource/vault.py
solvebio/test/test_object.py
solvebio/test/test_shortcuts.py
solvebio/test/test_vault.py

- update the upload and create-dataset shortcuts to require a dataset full path (breaking change that removes --vault and --path) from those commands
- add validation code to objects and vaults and add some incomplete path inference

update import and create-dataset shortcuts to require full path

---

solvebio/resource/manifest.py

add reader_params

---

solvebio/cli/data.py
solvebio/errors.py
solvebio/resource/dataset.py
solvebio/resource/object.py
solvebio/resource/vault.py

closes https://github.com/solvebio/solvebio-python/issues/229

include optional object type assertion when getting objects

---

solvebio/contrib/dash/solvebio_dash.py

Keep Dash scripts.config.serve_locally False

---

solvebio/query.py

Supports this:
```
dataset.query().export(format='json', target_full_path='my_vault:/path/to/my/json_files')
```

add target_full_path kwarg to export shortcut

---

solvebio/test/helper.py
solvebio/test/test_beacon.py
solvebio/test/test_dataset.py
solvebio/test/test_lookup.py
solvebio/test/test_query.py
solvebio/test/test_query_batch.py

We deleted some very old public data that these tests referenced and so they failed.
Now they rely on new data, so kicking the can down the road for now

Update tests reliant on deleted source data

---

solvebio/errors.py
solvebio/resource/object.py

Will retry on more status codes from amazon (recently saw a 400) and will also now raise an error when upload is unsuccessful, which is the desired behavior of the pipelines.

retry on more status codes, raise error when upload unsuccessful

---

CHANGELOG.md
solvebio/cli/data.py
solvebio/cli/main.py
solvebio/resource/object.py
solvebio/test/client_mocks.py
solvebio/test/test_object.py
solvebio/test/test_shortcuts.py

- Removes `--path` and `--vault` in favor of `--full-path` (--closes #224)
- Adds `--create-full-path` to create the upload destination if it does not exist (--closes #241)
- Adds `--exclude` parameter to exclude a list of paths (supports unix style globs) from uploading
- Adds `--dry-run` mode to evaluate before running
```
$ solvebio upload --help
usage: solvebio upload [-h] [--version] [--api-host API_HOST]
[--api-key API_KEY] [--api-token API_TOKEN]
[--full-path FULL_PATH] [--create-full-path]
[--exclude EXCLUDE [EXCLUDE ...]] [--dry-run]
local_path [local_path ...]
positional arguments:
local_path            The path to the local file or directory to upload
SolveBio Options:
-h, --help            show this help message and exit
--full-path FULL_PATH
The full path where the files and …
```

Upload CLI changes, Tag CLI, vault object shortcuts

---

solvebio/cli/data.py
solvebio/cli/main.py
solvebio/resource/manifest.py
solvebio/test/client_mocks.py
solvebio/test/test_shortcuts.py

- pass `--tag` values to add tags to the dataset
- pass `--metadata` vaults to add metadata key value paris
- pass `--metadata-json-file` to pass a JSON file of complex metadata
Breaking Changes
- fails if dataset already exists
- remove `vault` and `path` command overrides. Complete transition to `full_path`
- Inherits all new features above for creating datasets (via --create-dataset)
- pass `--remote-source` command toggles the `file` arguments to be remote paths
Breaking Changes 
- Inherits all breaking changes above for creating datasets (via --create-dataset)

Updates to "create-dataset" and "import" shortcut commands

---

solvebio/cli/data.py
solvebio/cli/main.py
solvebio/test/test_shortcuts.py

Builds off of https://github.com/solvebio/solvebio-python/pull/325
```
$ solvebio download --help
usage: solvebio download [-h] [--version] [--api-host API_HOST]
[--api-key API_KEY] [--access-token ACCESS_TOKEN]
[--dry-run]
full_path local_path
positional arguments:
local_path            The path to the local directory where to download
files.
full_path      The full path to the files on SolveBio. Supports Unix
style globs in order to download multiple files. Note:
Downloads are not recursive.
SolveBio Options:
-h, --help            show this help message and exit
--version             show program's version number and exit
--api-host API_HOST   Override the default SolveBio API host
--api-key API_KEY     Manually provide a SolveBio API key
--access-token ACCESS_TOKEN
Manually provide a …
```

CLI to download multiple files

---

solvebio/resource/object.py
solvebio/test/client_mocks.py
solvebio/test/test_object.py

Tags are case insensitive. Adds a helper method to the Object resource to check if a resource contains a tag. 
This is a common bit of code that gets written all over the place. 
```
if file.is_tagged("Special"):
do_special_things()
else:
pass
```

adds a shortcut to check if an object contains a tag

---

examples/import_data.py
solvebio/cli/data.py
solvebio/errors.py
solvebio/resource/dataset.py
solvebio/resource/object.py
solvebio/resource/vault.py
solvebio/test/client_mocks.py
solvebio/test/test_beacon.py
solvebio/test/test_dataset.py
solvebio/test/test_exports.py
solvebio/test/test_lookup.py
solvebio/test/test_object.py
solvebio/test/test_query.py
solvebio/test/test_query_batch.py
solvebio/test/test_shortcuts.py

Allows creating nested paths on the fly, which currently requires way too many lines of code. Takes the existing Dataset.get_or_create_by_full_path() and moves and upgrades it.
Also closes #326
Also closes #287

Object.get_or_create_by_full_path()

---

solvebio/__init__.py
solvebio/cli/credentials.py
solvebio/errors.py

Add more context to default error messages

Clean the netrc output format for the new "account" item

---

solvebio/resource/object.py
solvebio/test/client_mocks.py
solvebio/test/test_object.py

- fixes tag removal bug (resolves #347 )
- change `<object>.tag(my_tag)` command to save the tag by default (previously `apply_save=False` by default)
- add a shortcut `untag()` that removes a tag 
- allow a single tag in the `tag()` and `untag()` commands  (previously required a list)
- docs available here https://docs.solvebio.com/vaults/basics/#metadata-and-tags

Object tagging updates

---

solvebio/query.py
solvebio/test/test_query.py

- Fix the prefix issue when two fields after adding a prefix have the same name
- Add newly prefixed fields to the `explode_fields` list in order to be taken into an account for exploding.

Fix for multiple join errors

---

.travis.yml

Pypy is called pypy2 in bionic dist for Travis: https://docs.travis-ci.com/user/languages/python/#python-versions

Update Travis to Ubuntu 18.04

---

solvebio/query.py
solvebio/test/test_query.py

Handle the case where a join returns a list of lists. Instead of setting the data type to "object", flatten the results. This fixes issues that can come up when migrating the output of the join. 
closes #380 
Also, preserve annotator_params (specifically pre_annotation_expression) when running a join. This allows keys containing lists of values to be joined.

Flatten lists of lists instead of using "object" data type in joins

---

solvebio/query.py
solvebio/test/test_query.py

Slicing results of dataset/file query raises an error when the `stop` param is set to `float('inf').
closes #385

Handle a query slicing when the potential number of returned records in the query is larger than the number of records left in the dataset/file

---

solvebio/resource/object.py

fix default restore storage class issue and change to Standard-IA instead of Standard

---

examples/global_beacon_indexing.ipynb
examples/global_search.ipynb
solvebio/cli/ipython_init.py
solvebio/global_search.py
solvebio/query.py
solvebio/resource/dataset.py
solvebio/resource/object.py

- Return None by default if dataset doesn't contain Global Beacon:
Updated `Object.get_global_beacon_status` method so it returns `None` by default if Global Beacon doesn't exist.
```python
dataset = Object.get_by_full_path(dataset_full_path)
dataset.get_global_beacon_status()
dataset.get_global_beacon_status(raise_on_disabled=True)
```
- Alias methods in the Dataset class for Global Beacons:
Add ability to perform Global Beacon operations with the `Dataset` class:
```python
dataset = Dataset.get_by_full_path(dataset_full_path)
dataset.get_global_beacon_status()
dataset.enable_global_beacon()
dataset.disable_global_beacon()
```
- Subject method changes to accommodate API changes:
In `subjects()`/`subjects_count()` methods adding additional parameters in the api request `limit=0` and …

Global Beacon interface update

---

requirements-dev.txt
solvebio/global_search.py
solvebio/resource/object.py
solvebio/test/test_dataset_migrations.py

- Adds missing global search params (vault_scope, entities_match)
- Fix issue with querying objects directly from search results
- Fix issue with test environment dependencies

add new global search params (vault_scope and entities_match)

---

solvebio/cli/data.py
solvebio/cli/main.py
solvebio/resource/object.py
solvebio/test/test_object.py
solvebio/test/test_shortcuts.py

Ticket: https://precisionformedicine.atlassian.net/browse/BDSIM-411
Current uploads can be really slow if there are thousands of files to upload. Most of this time is IO bound waiting for API requests so we can implement some degree of parallelization. This implementation strategy allows users to specify the number of parallel processes via a CLI option (`--num-processes`).
This implementation _should_ preserve all original functionality by default and will only perform multiprocessing uploads if users specify a flag. Otherwise, uploads will still happen in a multiprocessing.Pool, but with only 1 parallel process.

BDSIM-411: Implement uploads in parallel via CLI

---

requirements-dev.txt
setup.py
solvebio/cli/data.py

The issue was related to the session object not being thread-safe. Previously, a single session object was shared across all processes making requests leading to really strange errors (e.g. ECONNRESET). 
This change creates a new session object for each process. I have tested this by running the following command to upload ~1000 files to an EDP instance:
```
solvebio upload --full-path "edp:Nishanth's Test Vault:/folder" ./source --num-processes 20 --create-full-path
```
Previously, this would fail immediately after creating the folders. Now, this entire process succeeds.

[EDPDEV-1000] Fix upload bug

---

solvebio/__init__.py

@davecap the new R client expects to find access tokens and credentials at `EDP_ACCESS_TOKEN` and `EDP_API_HOST` respectively. What do you think about adding this as a backup for this client?
This was also causing our vsim docker image to fail: https://precisionformedicine.atlassian.net/browse/EDPDEV-1075?focusedCommentId=155033

[EDPDEV-1075] Update env var token names

---

README.md
solvebio/client.py

This PR sets the connect parameter to the session Retry.
As per the documentation this should enable retries on dropped connections.
Linked ticket:
https://precisionformedicine.atlassian.net/browse/EDPDEV-1175
And added an explicit list of allowed methods.
This includes non-idempotent request - however imo if the retries only occur on 502 503 504 or a not established connection this should not cause an issue.

Add Connect to Client Retry Configuration

---

solvebio/cli/data.py
solvebio/cli/main.py

This pull request adds support for shortcuts when using the `ls` command.
The command would add `--follow-shortcuts` flag similar to `upload` and `download`

Add --follow-shortcuts to ls Command

---

solvebio/client.py

Reverts 18139f9c225868cccf9447e53848bd308dbd15f4 as we no longer require this for internal connections

revert EDPDEV-1696 require SSL for all connections

---

solvebio/cli/data.py
solvebio/global_search.py
solvebio/resource/object.py

EDPDEV-2749 - Fix upload command for nested folders when dry-run flag is active
EDPDEV-2789 - Fix subjects retrieval in GlobalSearch module
EDPDEV-2598 - Enhance solvebio download command to support one file download even if --recursive flag is active

[EDPDEV-2479][EDPDEV-2789][EDPDEV-2598]
