solvebio/solvebio-python

solvebio/test/test_beacon.py, solvebio/test/test_changelog.py
Added test cases for changelog on datasets and depository.
=> test_cases_changelog

solvebio/query.py
fixes issue with queries resulting in multiple queries in cases where filter is formatted incorrectly
=> fixes multiple queries with wrong filter closes #78

solvebio/resource/dataset.py, solvebio/test/test_lookup.py
added sbid lookup function for datasets and tests
=> added sbid lookup support in datasets - closes #81

solvebio/resource/dataset.py, solvebio/resource/datasetfield.py, solvebio/resource/depository.py, solvebio/resource/depositoryversion.py
=> makes datasets, depository versions, and depositories deletable

solvebio/contrib/vcf_parser/vcf_parser.py, solvebio/test/test_vcfparser.py
Also includes lenient VCF Reader to convert NaNs.
=> use pyvcf built-in file extension detection and gzip support

solvebio/resource/manifest.py
so its more obvious what went wrong
=> add invalid file path name in error 

solvebio/cli/data.py, solvebio/cli/ipython.py, solvebio/cli/main.py, solvebio/test/test_dataset.py, solvebio/test/test_lookup.py
fix an issue with loading credentials in CLI commands
=> add capacity argument to create-dataset command (closes #135)

solvebio/resource/upload.py, solvebio/test/test_upload.py
Also fixes minor issue with progress bar
=> Add retries to Upload creation (fixes #147)

solvebio/__init__.py, solvebio/cli/ipython.py, solvebio/query.py, solvebio/resource/__init__.py, solvebio/resource/dataset.py, solvebio/resource/datasetmigration.py, solvebio/test/helper.py, solvebio/test/test_dataset_migrations.py, solvebio/test/test_shortcuts.py
=> add DatasetMigration resource and migrate functions for Query and Dataset

solvebio/resource/datasetimport.py
=> update follow logic of imports now the commits are decoupled

.travis.yml
see https://blog.travis-ci.com/2017-04-17-precise-EOL
closes: #158
=> use new travis distribution: Ubuntu 14

solvebio/cli/data.py, solvebio/resource/dataset.py, solvebio/test/client_mocks.py, solvebio/test/test_dataset.py
=> remove genome build and is_genomic

solvebio/__init__.py, solvebio/cli/ipython.py, solvebio/resource/__init__.py, solvebio/resource/beacon.py, solvebio/resource/beaconset.py, solvebio/test/test_dataset.py
=> add basic BeaconSet and Beacon resources

solvebio/resource/manifest.py
include size, name, md5 and use `object_id` kwarg now
=> update manifest info

examples/import_data.py, solvebio/resource/dataset.py, solvebio/resource/object.py, solvebio/resource/vault.py
- example import script contained a deprecated function
- also pass a default description when uploading a file
=> update sample script

solvebio/__init__.py, solvebio/annotate.py, solvebio/cli/ipython.py, solvebio/client.py, solvebio/contrib/django_solvebio/admin.py, solvebio/contrib/vcf_parser/vcf_parser.py, solvebio/query.py, solvebio/resource/apiresource.py, solvebio/resource/beacon.py, solvebio/resource/beaconset.py, solvebio/resource/dataset.py, solvebio/resource/datasetfield.py, solvebio/resource/object.py, solvebio/resource/solveobject.py, solvebio/resource/vault.py, solvebio/test/helper.py, solvebio/test/test_annotate.py, solvebio/test/test_beacon.py, solvebio/test/test_client.py, solvebio/test/test_dataset.py, solvebio/test/test_dataset_migrations.py, solvebio/test/test_exports.py, solvebio/test/test_lookup.py, solvebio/test/test_query.py, solvebio/test/test_query_batch.py, solvebio/test/test_shortcuts.py, solvebio/test/test_vault.py
Ability to pass a custom client (with custom auth credentials) without using global state.
=> Support for isolated SolveClient (with non-global tokens)

solvebio/resource/apiresource.py, solvebio/resource/beacon.py, solvebio/resource/beaconset.py, solvebio/resource/dataset.py, solvebio/resource/datasetcommit.py, solvebio/resource/datasetexport.py, solvebio/resource/datasetfield.py, solvebio/resource/datasetimport.py, solvebio/resource/datasetmigration.py, solvebio/resource/datasettemplate.py, solvebio/resource/object.py, solvebio/resource/vault.py
Fixes issue where something could not be deleted if it wasn't set.
=> replace PRINTABLE_NAME with something dynamic

solvebio/resource/task.py
i introduced this bug in previous release https://github.com/solvebio/solvebio-python/commit/863fec4879718aed662705ca40bef9b1362a8b07#diff-e55e6e64d658813f862520f75a3b7996R20
=> [Bug] method turned property bug

solvebio/cli/main.py, solvebio/resource/manifest.py, solvebio/test/test_shortcuts.py, solvebio/utils/files.py
and also remove old file format requirements. file type will be validated server-side
=> better error if invalid path

solvebio/resource/object.py
=> fix client-passthrough for object validation

solvebio/resource/datasetmigration.py
Wrong URL was being printed here.
=> printing incorrect url

solvebio/cli/data.py, solvebio/resource/manifest.py, solvebio/resource/object.py, solvebio/resource/vault.py, solvebio/test/client_mocks.py, solvebio/test/test_shortcuts.py
Pass the vault full path instead of the vault name
closes #238
=> pass vault object through instead of vault name

solvebio/cli/auth.py, solvebio/resource/apiresource.py
Replaced six.moves.input() with raw_input() as 2to3 tool already futurizes raw_input()
closes #235
=> removed six import, changed input to raw_input

solvebio/resource/vault.py
=> Fix create_folder shortcut

solvebio/cli/auth.py, solvebio/cli/ipython.py, solvebio/cli/ipython_5_init.py, solvebio/cli/ipython_init.py
* Fix issue with globals in ipython shell (closes #257)
* Fix issue where login from shell does not load API key (closes #255)
=> Fix two issues with IPython shell

solvebio/resource/task.py, solvebio/test/test_exports.py
add task.cancel() and also makes Task undateable so that priority can be set
=> Update Task objects and add shortcut to cancel tasks

solvebio/annotate.py
Add ability to pass annotator_params into the annotate endpoint
closes #271
=> add annotator_params to annotate endpoint

solvebio/resource/object.py
=> Retry uploads up to 5 times

solvebio/query.py
Now you can convert a dataset to Pandas DataFrame: `pd.DataFrame.from_records(ds.query())`
=> Handle case where Query iterator has not been initialized (closes #286)

solvebio/query.py
The change in v2.8.1 broke Query.facets()
=> Revert change to Query.facets()

solvebio/contrib/dash/solvebio_auth.py
closes #296 
Changes include:
- Default expiry set to 1 week
- Expose `max_age` to allow custom expiry
=> Prevent cookie from expiring immediately

README.md, solvebio/cli/credentials.py, solvebio/client.py, solvebio/contrib/dash/solvebio_auth.py, solvebio/help.py, solvebio/resource/manifest.py, solvebio/utils/validators.py, tox.ini
=> Use six.moves to eliminate 2to3 issues (closes #299)

solvebio/contrib/dash/solvebio_dash.py
See #278 
Current version of Dash is at 1.0.0
=> Fix typo and pop salt before passing to SolveBioAuth

solvebio/resource/dataset.py, solvebio/resource/datasetcommit.py, solvebio/resource/datasetimport.py, solvebio/resource/datasetmigration.py, solvebio/resource/object_copy_task.py, solvebio/resource/task.py, solvebio/resource/vault_sync_task.py
- only get 1 Task in activity
- configure limit and sleep time
- sync across Tasks (closes #285)
- add commit follow to migrations
=> Task Activity improvements

solvebio/cli/data.py, solvebio/cli/main.py, solvebio/resource/object.py
- move tree traversal and tag() into Object class
- simplify dry_run and confirmation prompt code
=> clean up `solvebio tag` code

solvebio/__init__.py, solvebio/cli/auth.py, solvebio/cli/credentials.py, solvebio/cli/ipython_init.py, solvebio/cli/main.py, solvebio/client.py, solvebio/errors.py, solvebio/resource/object.py, solvebio/test/data/.gitignore, solvebio/test/test_credentials.py, solvebio/test/test_shortcuts.py, solvebio/utils/validators.py
* Support access tokens from CLI (closes #318)
* Support saving of access tokens
* Don't always save credentials
=> Access token improvements

solvebio/__init__.py, solvebio/cli/auth.py, solvebio/cli/ipython_init.py, solvebio/cli/main.py, solvebio/test/test_login.py
removes deprecated interactive shell login (and builds on #319 )
=> More login simplification

solvebio/cli/data.py, solvebio/cli/main.py, solvebio/test/test_shortcuts.py
This is a global shortcut/need. This code was pulled from NGS Tools.
=> add command to print out the active Task queue

.travis.yml, README.md
- unpin Travis build image
- add py3.7 and py3.8
- add pypy and pypy3
- remove py3.5
=> More travis builds

solvebio/errors.py
=> cleaner error handling

solvebio/errors.py, solvebio/test/test_errors.py
=> do not expect that error contains json

solvebio/query.py, solvebio/resource/dataset.py, solvebio/resource/object.py, solvebio/resource/savedquery.py, solvebio/test/client_mocks.py, solvebio/test/test_dataset_migrations.py, solvebio/test/test_shortcuts.py
Fix regression introduced by #331 (for #326)
=> Dataset.get_or_create_by_full_path should always return Dataset object

solvebio/cli/credentials.py, solvebio/resource/datasetmigration.py, solvebio/test/test_vault.py
Added logic for the protocol resolving.
=> Add protocol resolving logic

solvebio/errors.py, solvebio/test/test_errors.py
Failed to print error when the details contained a list of dicts
=> handle case where the error message contains a list of dicts

solvebio/resource/apiresource.py, solvebio/test/test_apiresource.py, solvebio/test/test_dataset.py, solvebio/test/test_object.py
=> Issue 276 dict attributes not save updates

public_recipes.yml, recipes/public.yml, recipes/sync_recipe_utils.py
all public recipes on the solvebio platform
=> Catalog of all public recipes

public_recipes.yml, recipes/public.yml, recipes/sync_recipe_utils.py, recipes/sync_recipes.py, recipes/tests/test_recipes_sync.py
Sync, delete and export modes can be used as subcommands:
solvebio-recipes sync --all path/to/yml
solvebio-recipes delete --name "dbsnp (v1.0.0)"
solvebio export --account-recipes path/to/yml
=> Sync recipes command refactoring

CHANGELOG.md, solvebio/query.py, solvebio/resource/dataset.py
* Updates follow logic to accommodate parallel migrations
=> Handle parallel migrations

solvebio/cli/data.py, solvebio/cli/main.py, solvebio/test/test_shortcuts.py
Initial idea... it works but it's missing a few key features:
- `--exclude` option
- delete (if doesn't exist in remote)
- `--dry-run` isn't functional right now
- Better print statements
- tests
=> BDSIM-373: Added recursive data download via sync

.github/workflows/python-package.yml, solvebio/test/helper.py, solvebio/test/test_apiresource.py, solvebio/test/test_beacon.py
Point to QA EDP endpoint and use quartzbio reference datasets
=> EDPDEV-1117 Switch API endpoint and datasets used for tests

solvebio/cli/credentials.py
Fixes this error: `TypeError: 'dict_keys' object is not subscriptable`
=> EDPDEV-1957 Fix python3 issue related to empty credentials file

solvebio/resource/apiresource.py, solvebio/resource/datasetcommit.py
Note that this change depends on backend API changes which are slated for release in Q1 2025.
=> EDPDEV-1535 add commit download support
